docker_flags = [ '-p', '8080:8080',
'--workdir=/home/$USER',
'--env=DISPLAY',
'--volume=/home/$USER:/home/$USER',
'--volume=/etc/group:/etc/group:ro',
'--volume=/etc/passwd:/etc/passwd:ro',
'--volume=/etc/shadow:/etc/shadow:ro',
'--volume=/etc/sudoers.d:/etc/sudoers.d:ro',
'--volume=/tmp/.X11-unix:/tmp/.X11-unix:rw'
]

image = 'python-gpu-jupyter'
variants = ['python3','gpu']